/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AsesoriaRouteImport } from './routes/asesoria'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CotizacionRouteImport } from './routes/cotizacion'
import { Route as IaRouteImport } from './routes/ia'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesoriaRoute = AsesoriaRouteImport.update({
  id: '/asesoria',
  path: '/asesoria',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionRoute = CotizacionRouteImport.update({
  id: '/cotizacion',
  path: '/cotizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/asesoria': typeof AsesoriaRoute
  '/blog': typeof BlogRoute
  '/carreras': typeof CarrerasRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/ia': typeof IaRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/asesoria': typeof AsesoriaRoute
  '/blog': typeof BlogRoute
  '/carreras': typeof CarrerasRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/ia': typeof IaRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/asesoria': typeof AsesoriaRoute
  '/blog': typeof BlogRoute
  '/carreras': typeof CarrerasRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/cotizacion': typeof CotizacionRoute
  '/ia': typeof IaRoute
  '/nosotros': typeof NosotrosRoute
  '/plataforma': typeof PlataformaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/asesoria'
    | '/blog'
    | '/carreras'
    | '/catalogo'
    | '/contacto'
    | '/cotizacion'
    | '/ia'
    | '/nosotros'
    | '/plataforma'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/asesoria'
    | '/blog'
    | '/carreras'
    | '/catalogo'
    | '/contacto'
    | '/cotizacion'
    | '/ia'
    | '/nosotros'
    | '/plataforma'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/asesoria'
    | '/blog'
    | '/carreras'
    | '/catalogo'
    | '/contacto'
    | '/cotizacion'
    | '/ia'
    | '/nosotros'
    | '/plataforma'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AsesoriaRoute: typeof AsesoriaRoute
  BlogRoute: typeof BlogRoute
  CarrerasRoute: typeof CarrerasRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  CotizacionRoute: typeof CotizacionRoute
  IaRoute: typeof IaRoute
  NosotrosRoute: typeof NosotrosRoute
  PlataformaRoute: typeof PlataformaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesoria': {
      id: '/asesoria'
      path: '/asesoria'
      fullPath: '/asesoria'
      preLoaderRoute: typeof AsesoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizacion': {
      id: '/cotizacion'
      path: '/cotizacion'
      fullPath: '/cotizacion'
      preLoaderRoute: typeof CotizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AsesoriaRoute: AsesoriaRoute,
  BlogRoute: BlogRoute,
  CarrerasRoute: CarrerasRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  CotizacionRoute: CotizacionRoute,
  IaRoute: IaRoute,
  NosotrosRoute: NosotrosRoute,
  PlataformaRoute: PlataformaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
